using DataLayer.AutoGeneratedCode;
using DataLayer.DataBaseManager;
using FileTrackingSystem.Repository.WebAdmin;
using FileTrackingSystem.ViewModel.WebAdmin;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using FileTrackingSystem.Repository.WebAdmin;

namespace FileTrackingSystem.Controllers
{
    public partial class WebAdminController
    {
        #region EmployeeMaster
        public IActionResult EmployeeMaster()
        {
            WebAdminRepository webAdminRepository = new WebAdminRepository();
            var model = webAdminRepository.GetEmployees();
            return View(model);
        }

        [HttpPost]
        public IActionResult EmployeeMaster(WebAdminEmployeeMasterViewModel model)
        {
            WebAdminRepository webAdminRepository = new WebAdminRepository();
            webAdminRepository.Save(model);
            return RedirectToAction("EmployeeMaster");
        }

        [HttpGet]
        public IActionResult EmployeeMasterDelete(int id)
        {
            WebAdminRepository webAdminRepository = new WebAdminRepository();
            webAdminRepository.Delete(id);
            return RedirectToAction("EmployeeMaster");
        }
        #endregion
    }
}
