using DataLayer.AutoGeneratedCode;
using FileTrackingSystem.ViewModel.OfficeAdmin;
using FileTrackingSystem.ViewModel.WebAdmin;

namespace FileTrackingSystem.Extensions
{
    public static class Extensions
    {

        public static void CreateEmployeeMasterObject(this EmployeeMaster employeeMaster, WebAdminEmployeeMasterViewModel emp)
        {
            employeeMaster.Id = emp.Id;
            employeeMaster.Name = emp.Name;
            employeeMaster.Designation = emp.Designation;
            employeeMaster.DeptId = emp.DeptId;
            employeeMaster.Email = emp.Email;
            employeeMaster.Password = emp.Password;
            employeeMaster.Dob = emp.Dob;
            employeeMaster.IsDeleted = emp.IsDeleted;
            employeeMaster.Dept = new DepartmentMaster();
            employeeMaster.Dept.Name = emp.DepartmentName;
        }

        public static void CreateOfficeMasterObject(this OfficeMaster officeMaster, OfficeAdminOfficeMasterViewModel office)
        {
            officeMaster.Id=office.Id;
            officeMaster.Address = office.Address;
            officeMaster.Ddocode = office.Ddocode;
            officeMaster.OfficeName=office.OfficeName;
            officeMaster.Contact1 = office.Contact1;
            officeMaster.Contact2=office.Contact2;
            officeMaster.ContactPersonName=office.ContactPersonName;
            officeMaster.District=office.District;
            officeMaster.Email=office.Email;
            officeMaster.WebSite=office.WebSite;
            officeMaster.IsDeleted=office.IsDeleted;
            officeMaster.Fax = office.Fax;
            officeMaster.IsActive=office.IsActive;
            officeMaster.PinCode = office.PinCode;
            officeMaster.OfficeTypeId=office.OfficeTypeId;
        }

        public static void CreateEmployeeMasterForOfficeAdmin(this UserMaster employeeMaster, OfficeAdminEmployeeMasterViewModel emp)
        {
            employeeMaster.Id = emp.Id;
            employeeMaster.Name = emp.Name;
            employeeMaster.Email = emp.Email;
            employeeMaster.MobileNumber = emp.MobileNumber;
            employeeMaster.Password = emp.Password;
            employeeMaster.Designation = emp.Designation;
            employeeMaster.Section = emp.Section;
            employeeMaster.RegisterDateTime = emp.RegisterDateTime;
            employeeMaster.RoleId = emp.RoleId;
            employeeMaster.Gender = emp.Gender;
            employeeMaster.BirthDate = emp.BirthDate;
            employeeMaster.FaxNo = emp.FaxNo;
            employeeMaster.AdharCardNo = emp.AdharCardNo;
            employeeMaster.IsDeleted = emp.IsDeleted;
        }
    }
}
