using System;
using System.Collections.Generic;

namespace FileTrackingSystem.AutoGeneratedCode
{
    public partial class Acceptance
    {
        public Acceptance()
        {
            Inwards = new HashSet<Inward>();
        }

        public int Id { get; set; }
        public string? Status { get; set; }

        public virtual ICollection<Inward> Inwards { get; set; }
    }
}
