using System;
using System.Collections.Generic;

namespace FileTrackingSystem.AutoGeneratedCode
{
    public partial class Cc
    {
        public Cc()
        {
            Inwards = new HashSet<Inward>();
            Outwards = new HashSet<Outward>();
        }

        public int Id { get; set; }
        public string? Designation { get; set; }

        public virtual ICollection<Inward> Inwards { get; set; }
        public virtual ICollection<Outward> Outwards { get; set; }
    }
}
