using System;
using System.Collections.Generic;

namespace FileTrackingSystem.AutoGeneratedCode
{
    public partial class Classification
    {
        public Classification()
        {
            Inwards = new HashSet<Inward>();
        }

        public int Id { get; set; }
        public string? Description { get; set; }

        public virtual ICollection<Inward> Inwards { get; set; }
    }
}
