using System;
using System.Collections.Generic;

namespace FileTrackingSystem.AutoGeneratedCode
{
    public partial class Designation
    {
        public Designation()
        {
            Inwards = new HashSet<Inward>();
        }

        public int Id { get; set; }
        public string? Type { get; set; }
        public bool? IsDeleted { get; set; }

        public virtual ICollection<Inward> Inwards { get; set; }
    }
}
