using System;
using System.Collections.Generic;

namespace FileTrackingSystem.AutoGeneratedCode
{
    public partial class District
    {
        public District()
        {
            Talukas = new HashSet<Taluka>();
        }

        public int Id { get; set; }
        public string Name { get; set; } = null!;

        public virtual ICollection<Taluka> Talukas { get; set; }
    }
}
