using System;
using System.Collections.Generic;

namespace FileTrackingSystem.AutoGeneratedCode
{
    public partial class EmployeeMaster
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public string? Designation { get; set; }
        public int? DeptId { get; set; }
        public string? Email { get; set; }
        public string? Password { get; set; }
        public DateTime? Dob { get; set; }
        public bool? IsDeleted { get; set; }

        public virtual DepartmentMaster? Dept { get; set; }
    }
}
