using System;
using System.Collections.Generic;

namespace FileTrackingSystem.AutoGeneratedCode
{
    public partial class Inward
    {
        public Inward()
        {
            InwardOutwards = new HashSet<InwardOutward>();
        }

        public int Id { get; set; }
        public DateTime? Date { get; set; }
        public int? ReferenceNo { get; set; }
        public DateTime? ReferenceDate { get; set; }
        public string? InwardFrom { get; set; }
        public int? SubjectId { get; set; }
        public int? ClassificationId { get; set; }
        public int? SectionId { get; set; }
        public int? UserId { get; set; }
        public int? StatusId { get; set; }
        public string? Remark { get; set; }
        public int? Ccid { get; set; }
        public string? Cc3 { get; set; }
        public int? AcceptanceId { get; set; }
        public DateTime? AcceptedDate { get; set; }
        public DateTime? ReassignDate { get; set; }
        public DateTime? CompleteDate { get; set; }
        public DateTime? StatusChangeDate { get; set; }
        public int? InwardPriority { get; set; }
        public int? SendToOutward { get; set; }
        public int? ReasonId { get; set; }
        public int? DesignationId { get; set; }

        public virtual Acceptance? Acceptance { get; set; }
        public virtual Cc? Cc { get; set; }
        public virtual Classification? Classification { get; set; }
        public virtual Designation? Designation { get; set; }
        public virtual Reason? Reason { get; set; }
        public virtual Status? Status { get; set; }
        public virtual Subject? Subject { get; set; }
        public virtual UserMaster? User { get; set; }
        public virtual ICollection<InwardOutward> InwardOutwards { get; set; }
    }
}
