using System;
using System.Collections.Generic;

namespace FileTrackingSystem.AutoGeneratedCode
{
    public partial class Letter
    {
        public int Id { get; set; }
        public string? Type { get; set; }
        public bool? IsDeleted { get; set; }
    }
}
