using System;
using System.Collections.Generic;

namespace FileTrackingSystem.AutoGeneratedCode
{
    public partial class ModeOfDispatch
    {
        public ModeOfDispatch()
        {
            Outwards = new HashSet<Outward>();
        }

        public int Id { get; set; }
        public string? Name { get; set; }

        public virtual ICollection<Outward> Outwards { get; set; }
    }
}
