using System;
using System.Collections.Generic;

namespace FileTrackingSystem.AutoGeneratedCode
{
    public partial class OfficeType
    {
        public OfficeType()
        {
            OfficeMasters = new HashSet<OfficeMaster>();
        }

        public int Id { get; set; }
        public string? Name { get; set; }
        public string? Type { get; set; }
        public bool? IsDeleted { get; set; }

        public virtual ICollection<OfficeMaster> OfficeMasters { get; set; }
    }
}
