using System;
using System.Collections.Generic;

namespace FileTrackingSystem.AutoGeneratedCode
{
    public partial class Outward
    {
        public Outward()
        {
            InwardOutwards = new HashSet<InwardOutward>();
        }

        public int Id { get; set; }
        public DateTime? Date { get; set; }
        public int? ReferenceNo { get; set; }
        public int? SubjectId { get; set; }
        public string? OutwardTo { get; set; }
        public int? Ccid { get; set; }
        public int? DispatchId { get; set; }
        public int? PostageChanges { get; set; }
        public int? UserId { get; set; }
        public DateTime? DispatchDate { get; set; }
        public string? Remark { get; set; }
        public int? AcceptanceId { get; set; }
        public DateTime? CompleteDate { get; set; }

        public virtual Cc? Cc { get; set; }
        public virtual ModeOfDispatch? Dispatch { get; set; }
        public virtual Subject? Subject { get; set; }
        public virtual ICollection<InwardOutward> InwardOutwards { get; set; }
    }
}
