using System;
using System.Collections.Generic;

namespace FileTrackingSystem.AutoGeneratedCode
{
    public partial class Reason
    {
        public Reason()
        {
            Inwards = new HashSet<Inward>();
        }

        public int Id { get; set; }
        public string? Designation { get; set; }

        public virtual ICollection<Inward> Inwards { get; set; }
    }
}
