using System;
using System.Collections.Generic;

namespace FileTrackingSystem.AutoGeneratedCode
{
    public partial class Role
    {
        public Role()
        {
            UserMasters = new HashSet<UserMaster>();
        }

        public int Id { get; set; }
        public string? Role1 { get; set; }
        public bool? IsActive { get; set; }

        public virtual ICollection<UserMaster> UserMasters { get; set; }
    }
}
