using System;
using System.Collections.Generic;

namespace FileTrackingSystem.AutoGeneratedCode
{
    public partial class Section
    {
        public int Id { get; set; }
        public string? Name { get; set; }
    }
}
