using System;
using System.Collections.Generic;

namespace FileTrackingSystem.AutoGeneratedCode
{
    public partial class TblExceptionLoggingToDataBase
    {
        public long LogId { get; set; }
        public string? ExceptionMsg { get; set; }
        public string? ExceptionType { get; set; }
        public string? ExceptionSource { get; set; }
        public string? ExceptionUrl { get; set; }
        public int? UserId { get; set; }
        public DateTime? Logdate { get; set; }
    }
}
