using System;
using System.Collections.Generic;

namespace FileTrackingSystem.AutoGeneratedCode
{
    public partial class Year
    {
        public int Id { get; set; }
        public string? Year1 { get; set; }
        public bool? IsDeleted { get; set; }
    }
}
