using DataLayer.AutoGeneratedCode;

namespace FileTrackingSystem.ViewModel.OfficeAdmin
{
    public class OfficeAdminStatusViewMaster
    {
        public List<Status> Statuses { get; set; }
        public string? Description { get; set; }
        public bool? IsDeleted { get; set; }
    }
}
