using DataLayer.AutoGeneratedCode;

namespace FileTrackingSystem.ViewModel.OfficeAdmin
{
    public class OfficeAdminSubjectViewModel
    {
        public List<Subject> Subjects { get; set; }
        public string? Name { get; set; }
        public string? SubName { get; set; }
        public bool? IsDeleted { get; set; }
    }
}
