using DataLayer.AutoGeneratedCode;

namespace FileTrackingSystem.ViewModel.OfficeAdmin
{
    public class OfficeAdminYearViewModel
    {
        public List<Year> Years { get; set; }
        public bool IsDeleted { get; set; }
        public string? Year1 { get; set; }
    }
}
