using DataLayer.AutoGeneratedCode;

namespace FileTrackingSystem.ViewModel.OfficeAdmin
{
    public class OfficeAdminEmployeeMasterViewModel
    {
        public List<UserMaster> Employees { get; set; }
        public List<Designation> Designations { get; set; }

        public List<OfficeMaster> officeMasters { get; set; }
        public List<DepartmentMaster> departmentMasters { get; set; }


        public int Id { get; set; }
        public string? Name { get; set; }
        public string? Email { get; set; }
        public string? MobileNumber { get; set; }
        public string? Password { get; set; }
        public string? Designation { get; set; }
        public string? Section { get; set; }
        public DateTime? RegisterDateTime { get; set; }
        public int? RoleId { get; set; }
        public string? Gender { get; set; }
        public DateTime? BirthDate { get; set; }
        public string? FaxNo { get; set; }
        public string? AdharCardNo { get; set; }
        public Boolean? IsDeleted { get; set; }


    }
}
