using DataLayer.AutoGeneratedCode;

namespace FileTrackingSystem.ViewModel.OfficeAdmin
{
    public class OfficeAdminOutwardViewModel
    {
        public List<Outward> outwards { get; set; }
    }
}
