using DataLayer.AutoGeneratedCode;

namespace FileTrackingSystem.ViewModel.OfficeAdmin
{
    public class OfficeAdminOfficeMasterViewModel
    {
        public List<OfficeMaster> officeMasters { get; set; }
        public List<OfficeType> officeType { get; set; }
        public int Id { get; set; }
        public string? OfficeName { get; set; }
        public string? Address { get; set; }
        public string? Taluka { get; set; }
        public string? District { get; set; }
        public string? Contact1 { get; set; }
        public string? Contact2 { get; set; }
        public string? Email { get; set; }
        public bool? IsActive { get; set; }
        public int? OfficeTypeId { get; set; }
        public int? RegionalOfficeId { get; set; }
        public int? Ddocode { get; set; }
        public int? PinCode { get; set; }
        public string? Fax { get; set; }
        public string? WebSite { get; set; }
        public int? OfficeId { get; set; }
        public string? Village { get; set; }
        public string? ContactPersonName { get; set; }
        public bool? IsDeleted { get; set; }
    }

    public class OfficeAdminOfficeTypeViewModel
    {
        public List<OfficeType> officeTypes { get; set; }
        public string? Name { get; set; }
        public string? Type { get; set; }
        public bool? IsDeleted { get; set; }
    }
}
