using DataLayer.AutoGeneratedCode;

namespace FileTrackingSystem.ViewModel.OfficeAdmin
{
    public class OfficeAdminDesignationMasterViewModel
    {
        public List<Designation> Designations { get; set; }
        public string? Type { get; set; }
        public bool? IsDeleted { get; set; }
    }
}
