using DataLayer.AutoGeneratedCode;

namespace FileTrackingSystem.ViewModel.OfficeAdmin
{
    public class OfficeAdminDepartmentViewModel
    {
        public List<DepartmentMaster> Departments { get; set; }
        public int Id { get; set; }
        public string? Name { get; set; }
        public bool? IsDeleted { get; set; }

    }
}
