using DataLayer.AutoGeneratedCode;
namespace FileTrackingSystem.ViewModel.WebAdmin
{
    public class WebAdminSubjectMasterViewModel
    {
        public List<Subject> subjects { get; set; }

        public Subject subjectes { get; set; }

    }
}
