using DataLayer.AutoGeneratedCode;

namespace FileTrackingSystem.ViewModel.WebAdmin
{
    public class WebAdminStatusMasterViewModel
    {
        public List<Status> statuses { get; set; }

        public Status status { get; set; }
    }
}
