using DataLayer.AutoGeneratedCode;
namespace FileTrackingSystem.ViewModel.WebAdmin
{
    public class WebAdminLetterMasterViewModel
    {
        public List<Letter> Letters { get; set; }

        public Letter letter { get; set; }
    }
}
