using DataLayer.AutoGeneratedCode;
namespace FileTrackingSystem.ViewModel.WebAdmin
{
    public class WebAdminDesignationMasterViewModel
    {
        public List<Designation> DesignationtMasters { get; set; }

        public Designation DesignationMaster { get; set; }


    }
}
