using DataLayer.AutoGeneratedCode;

namespace FileTrackingSystem.ViewModel.WebAdmin
{
    public class WebAdminOfficeTypeViewModel
    {
        public List<OfficeType> offices { get; set; }

        public OfficeType officers { get; set; }


    }
}
