using DataLayer.AutoGeneratedCode;

namespace FileTrackingSystem.ViewModel.WebAdmin
{
    public class WebAdminDepartmentMasterViewModel
    {
        public List<DepartmentMaster> Departments { get; set; }
        public DepartmentMaster Department { get; set; }

    }
}
