using DataLayer.AutoGeneratedCode;

namespace FileTrackingSystem.ViewModel.WebAdmin
{
    public class WebAdminEmployeeMasterViewModel
    {
        public WebAdminEmployeeMasterViewModel()
        {

        }
        public WebAdminEmployeeMasterViewModel(EmployeeMaster emp)
        {
            this.Id = emp.Id;
            this.Name = emp.Name;
            this.Designation = emp.Designation;
            this.DeptId = emp.DeptId;
            this.Email = emp.Email;
            this.Password = emp.Password;
            this.Dob = emp.Dob;
            this.IsDeleted = emp.IsDeleted;
            this.DepartmentName = emp.Dept.Name;
        }
       
        public int Id { get; set; }
        public string? Name { get; set; }
        public string? Designation { get; set; }
        public int? DeptId { get; set; }
        public string? Email { get; set; }
        public string? Password { get; set; }
        public DateTime? Dob { get; set; }
        public bool? IsDeleted { get; set; }
        public string DepartmentName { get; set; }
        public List<EmployeeMaster> EmployeeMasters { get; set; }
       
    }
}
