using DataLayer.AutoGeneratedCode;
namespace FileTrackingSystem.ViewModel.WebAdmin
{
    public class WebAdminYearMasterViewModel
    {
        public List<Year> Years { get; set; }
        public Year Year { get; set; }
    }
}
