using System;
using System.Collections.Generic;

namespace DataLayer.AutoGeneratedCode
{
    public partial class Acceptance
    {
        public int Id { get; set; }
        public string? Status { get; set; }
    }
}
