using System;
using System.Collections.Generic;

namespace DataLayer.AutoGeneratedCode
{
    public partial class Cc
    {
        public int Id { get; set; }
        public string? Designation { get; set; }
    }
}
