using System;
using System.Collections.Generic;

namespace DataLayer.AutoGeneratedCode
{
    public partial class Classification
    {
        public int Id { get; set; }
        public string? Description { get; set; }
    }
}
