using System;
using System.Collections.Generic;

namespace DataLayer.AutoGeneratedCode
{
    public partial class DepartmentMaster
    {
        public DepartmentMaster()
        {
            EmployeeMasters = new HashSet<EmployeeMaster>();
        }

        public int Id { get; set; }
        public string? Name { get; set; }
        public bool? IsDeleted { get; set; }

        public virtual ICollection<EmployeeMaster> EmployeeMasters { get; set; }
    }
}
