using System;
using System.Collections.Generic;

namespace DataLayer.AutoGeneratedCode
{
    public partial class Employee
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public string? Designation { get; set; }
        public string? Department { get; set; }
        public string? Email { get; set; }
        public string? Password { get; set; }
        public DateTime? Dob { get; set; }
        public bool IsDeleted { get; set; }
    }
}
