using System;
using System.Collections.Generic;

namespace DataLayer.AutoGeneratedCode
{
    public partial class Inward
    {
        public int Id { get; set; }
        public DateTime? Date { get; set; }
        public int? ReferenceNo { get; set; }
        public DateTime? ReferenceDate { get; set; }
        public string? InwardFrom { get; set; }
        public int? SubjectId { get; set; }
        public int? ClassificationId { get; set; }
        public int? SectionId { get; set; }
        public int? UserId { get; set; }
        public int? StatusId { get; set; }
        public string? Remark { get; set; }
        public int? Ccid { get; set; }
        public string? Cc3 { get; set; }
        public int? AcceptanceId { get; set; }
        public DateTime? AcceptedDate { get; set; }
        public DateTime? ReassignDate { get; set; }
        public DateTime? CompleteDate { get; set; }
        public DateTime? StatusChangeDate { get; set; }
        public int? InwardPriority { get; set; }
        public int? SendToOutward { get; set; }
        public int? ReasonId { get; set; }
    }
}
