using System;
using System.Collections.Generic;

namespace DataLayer.AutoGeneratedCode
{
    public partial class InwardOutward
    {
        public int Id { get; set; }
        public int? InwardId { get; set; }
        public int? OutwardId { get; set; }
    }
}
