using System;
using System.Collections.Generic;

namespace DataLayer.AutoGeneratedCode
{
    public partial class ModeOfDispatch
    {
        public int Id { get; set; }
        public string? Name { get; set; }
    }
}
