using System;
using System.Collections.Generic;

namespace DataLayer.AutoGeneratedCode
{
    public partial class OfficeType
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public string? Type { get; set; }
        public bool? IsDeleted { get; set; }
    }
}
