using System;
using System.Collections.Generic;

namespace DataLayer.AutoGeneratedCode
{
    public partial class Outward
    {
        public int Id { get; set; }
        public DateTime? Date { get; set; }
        public int? ReferenceNo { get; set; }
        public int? SubjectId { get; set; }
        public string? OutwardTo { get; set; }
        public int? Ccid { get; set; }
        public int? DispatchId { get; set; }
        public int? PostageChanges { get; set; }
        public int? UserId { get; set; }
        public DateTime? DispatchDate { get; set; }
        public string? Remark { get; set; }
        public int? AcceptanceId { get; set; }
        public DateTime? CompleteDate { get; set; }
    }
}
