using System;
using System.Collections.Generic;

namespace DataLayer.AutoGeneratedCode
{
    public partial class Status
    {
        public int Id { get; set; }
        public string? Description { get; set; }
        public bool? IsDeleted { get; set; }
    }
}
