using System;
using System.Collections.Generic;

namespace DataLayer.AutoGeneratedCode
{
    public partial class UserMaster
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public string? Email { get; set; }
        public string? MobileNumber { get; set; }
        public string? Password { get; set; }
        public string? Designation { get; set; }
        public string? Section { get; set; }
        public DateTime? RegisterDateTime { get; set; }
        public int? RoleId { get; set; }
        public string? Gender { get; set; }
        public DateTime? BirthDate { get; set; }
        public string? FaxNo { get; set; }
        public string? AdharCardNo { get; set; }
        public Boolean? IsDeleted { get; set; }

        public virtual Role? Role { get; set; }
    }
}
